{
 "title": "RabbitMQ",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "system_uptime" } },
   { "name": "ident", "label": "Ident", "query": { "query": "system_uptime" } }
  ]
 },
 "panels": [
  {
   "title": "概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "就绪消息",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_ready_gauge{application=\"$application\", ident=\"$ident\"})"
      }
     ]
    },
    {
     "title": "传入消息(每秒)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_published_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))"
      }
     ]
    },
    {
     "title": "生产者",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_channels_gauge{application=\"$application\", ident=\"$ident\"}) - (sum(rabbitmq_channel_consumers_gauge{application=\"$application\", ident=\"$ident\"}) - 0)"
      }
     ]
    },
    {
     "title": "连接",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rabbitmq_connections_gauge{application=\"$application\", ident=\"$ident\"}"
      }
     ]
    },
    {
     "title": "队列",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rabbitmq_queues_gauge{application=\"$application\", ident=\"$ident\"}"
      }
     ]
    },
    {
     "title": "未确认消息",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_unacked_gauge{application=\"$application\", ident=\"$ident\"})"
      }
     ]
    },
    {
     "title": "传出消息(每秒)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_redelivered_total_counter{application=\"$application\",ident=\"$ident\"}[60s])) + sum(rate(rabbitmq_channel_messages_delivered_total_counter{application=\"$application\",ident=\"$ident\"}[60s])) + sum(rate(rabbitmq_channel_messages_delivered_ack_total_counter{application=\"$application\",ident=\"$ident\"}[60s])) + sum(rate(rabbitmq_channel_get_total_counter{application=\"$application\",ident=\"$ident\"}[60s])) + sum(rate(rabbitmq_channel_get_ack_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))\r\n"
      }
     ]
    },
    {
     "title": "消费者",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rabbitmq_channel_consumers_gauge{application=\"$application\", ident=\"$ident\"})"
      }
     ]
    },
    {
     "title": "信道",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rabbitmq_channels_gauge{application=\"$application\", ident=\"$ident\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "节点信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "版本信息",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rabbitmq_build_info_value{application=\"$application\", ident=\"$ident\"} - 0"
      }
     ]
    },
    {
     "title": "可用内存",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rabbitmq_resident_memory_limit_bytes_gauge{application=\"$application\", ident=\"$ident\"} - rabbitmq_process_resident_memory_bytes_gauge{application=\"$application\", ident=\"$ident\"}"
      }
     ]
    },
    {
     "title": "可用磁盘空间",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rabbitmq_disk_space_available_bytes_gauge{application=\"$application\", ident=\"$ident\"}"
      }
     ]
    },
    {
     "title": "可用文件描述符",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rabbitmq_process_max_fds_gauge{application=\"$application\",ident=\"$ident\"} - rabbitmq_process_open_fds_gauge{application=\"$application\",ident=\"$ident\"}"
      }
     ]
    },
    {
     "title": "可用TCP 套接字",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rabbitmq_process_max_tcp_sockets_gauge{application=\"$application\",ident=\"$ident\"} - rabbitmq_process_open_tcp_sockets_gauge{application=\"$application\",ident=\"$ident\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "队列消息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "准备好传递给消费者的消息",
     "type": "timeseries",
     "description": "准备好传递给消费者的就绪消息总数。\n\n旨在使该值尽可能低。 当消息流过它时，RabbitMQ 表现最好。 发布者偶尔超过消费者是可以的，但期望消费者最终会处理所有准备好的消息。\n\n如果此指标不断增加，您的系统最终将耗尽内存和/或磁盘空间。 考虑使用 TTL 或队列长度限制来防止无限制的消息增长。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_ready_gauge{application=\"$application\",ident=\"$ident\"})",
       "legendFormat": "消息数"
      }
     ]
    },
    {
     "title": "等待消费者确认的消息",
     "type": "timeseries",
     "description": "正在发送给消费者、当前正在由消费者处理或只是等待队列处理消费者确认的消息总数。 在队列处理消息确认之前，该消息将保持未确认状态。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(rabbitmq_queue_messages_unacked_gauge{application=\"$application\",ident=\"$ident\"})",
       "legendFormat": "消息数"
      }
     ]
    }
   ]
  },
  {
   "title": "传入消息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "生产消息(每秒)",
     "type": "timeseries",
     "description": "应用任何路由规则之前的传入消息速率。\n\n如果此值小于生产到队列的消息数，则可能表明某些消息被传递到多个队列。\n\n如果此值高于生产到队列的消息数，则无法路由消息并将被丢弃或返回给生产者。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_published_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "消息数"
      }
     ]
    },
    {
     "title": "向生产者确认的消息(每秒)",
     "type": "timeseries",
     "description": "代理向生产者确认消息的速率。 生产者必须选择接收消息确认。\n\n如果此指标始终为零，则可能表明客户端未使用生产者确认。 已发布消息的安全性可能存在风险。",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_confirmed_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "消息数"
      }
     ]
    },
    {
     "title": "成功路由到队列的消息速率(每秒)",
     "type": "timeseries",
     "description": "从生产者接收并成功路由到主队列副本的消息的速率。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_queue_messages_published_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "消息数"
      }
     ]
    },
    {
     "title": "未向生产者确认的消息(每秒)",
     "type": "timeseries",
     "description": "从开启“生产者确认”，代理未确认的生产者接收到消息的速率。",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_unconfirmed_gauge{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "消息数"
      }
     ]
    },
    {
     "title": "无法路由和被丢弃的消息(每秒)",
     "type": "timeseries",
     "description": "无法路由和丢弃的消息的速率。\n\n任何高于零的值都意味着消息丢失，并且可能表明生产者端存在路由问题。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_unroutable_dropped_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "消息数"
      }
     ]
    },
    {
     "title": "无法路由并返回给生产者的消息(每秒)",
     "type": "timeseries",
     "description": "无法路由并返回给生产者的消息的比率。\n\n高于零的持续值可能表明发布者端存在路由问题。",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_unroutable_returned_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "消息数"
      }
     ]
    }
   ]
  },
  {
   "title": "传出消息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "传递给消费者的消息(每秒)",
     "type": "timeseries",
     "description": "传递给消费者的消息的速率。 它包括已重新传递的消息。\n\n该指标不包括消费者使用“basic.get”（通过轮询消费）获取的消息。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_delivered_total_counter{application=\"$application\",ident=\"$ident\"}[60s]) + rate(rabbitmq_channel_messages_delivered_ack_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "消息数"
      }
     ]
    },
    {
     "title": "已重新传递给消费者的消息(每秒)",
     "type": "timeseries",
     "description": "已重新传递给消费者的消息的速率。 它包括由于通道异常或连接关闭而自动重新排队和重新传递的消息。\n\n预计会有一些重新交付，但如果该指标始终非零，则值得调查原因。",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_redelivered_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "消息数"
      }
     ]
    },
    {
     "title": "向使用手动确认模式的消费者传递的消息(每秒)",
     "type": "timeseries",
     "description": "向使用手动确认模式的消费者传递消息的速率。\n\n使用此模式时，RabbitMQ 会等待消费者确认消息，然后才能传递更多消息。\n\n这是使用消息的最安全方式。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_delivered_ack_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "消息数"
      }
     ]
    },
    {
     "title": "向使用自动确认模式的消费者传递的消息(每秒)",
     "type": "timeseries",
     "description": "向使用自动确认模式的消费者传递消息的速率。\n\n使用此模式时，RabbitMQ 不会等待消费者确认消息传递。\n\n这种模式是即发即弃的，不提供任何交付安全保证。 它倾向于提供更高的吞吐量，并且可能导致消费者过载和更高的消费者内存使用率。",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_delivered_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "消息数"
      }
     ]
    },
    {
     "title": "来自使用手动确认模式的消费者的消息确认(每秒)",
     "type": "timeseries",
     "description": "来自使用手动确认模式的消费者的消息确认率。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_messages_acked_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "消息数"
      }
     ]
    },
    {
     "title": "传递给使用自动确认模式的轮询消费者的消息(每秒)",
     "type": "timeseries",
     "description": "传递给使用自动确认模式的轮询消费者的消息的速率。\n\n轮询消费者的使用效率非常低，因此强烈反对。",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_get_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "消息数"
      }
     ]
    },
    {
     "title": "不产生结果的轮询消费者操作(每秒)",
     "type": "timeseries",
     "description": "不产生结果的轮询消费者操作的速率。\n\n任何大于零的值都意味着 RabbitMQ 资源被轮询消费者浪费了。\n\n将此指标与其他轮询消费者指标进行比较，以查看低效率。\n\n轮询消费者的使用效率非常低，因此强烈反对。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_get_empty_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "消息数"
      }
     ]
    },
    {
     "title": "传递给使用手动确认模式的轮询消费者的消息(每秒)",
     "type": "timeseries",
     "description": "传递给使用手动确认模式的轮询消费者的消息的速率。\n\n轮询消费者的使用效率非常低，因此强烈反对。",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channel_get_ack_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "消息数"
      }
     ]
    }
   ]
  },
  {
   "title": "队列",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "队列",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "rabbitmq_queue_messages_gauge{application=\"$application\",ident=\"$ident\"} - 0"
      }
     ]
    },
    {
     "title": "队列声明(每秒)",
     "type": "timeseries",
     "description": "客户端执行队列声明的速率。\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_queues_declared_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "队列数"
      }
     ]
    },
    {
     "title": "队列创建(每秒)",
     "type": "timeseries",
     "description": "创建新队列的速率（相对于重新声明）。\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_queues_created_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "队列数"
      }
     ]
    },
    {
     "title": "队列删除(每秒)",
     "type": "timeseries",
     "description": "队列删除的速率。",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_queues_deleted_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "队列数"
      }
     ]
    }
   ]
  },
  {
   "title": "信道",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "信道",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "rabbitmq_channel_consumers_gauge{application=\"$application\",ident=\"$ident\"} - 0"
      }
     ]
    },
    {
     "title": "新信道(每秒)",
     "type": "timeseries",
     "description": "应用程序在所有连接中打开新信道的速率。 预计信道将长期存在。",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channels_opened_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "信道数"
      }
     ]
    },
    {
     "title": "关闭信道(每秒)",
     "type": "timeseries",
     "description": "应用程序在所有连接中关闭信道的速率。",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_channels_closed_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "信道数"
      }
     ]
    }
   ]
  },
  {
   "title": "连接",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "连接",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rabbitmq_connection_incoming_packets_total_counter{application=\"$application\",ident=\"$ident\"} - 0"
      }
     ]
    },
    {
     "title": "新连接(每秒)",
     "type": "timeseries",
     "description": "客户端打开新连接的速率。 预计连接将是长期存在的。",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_connections_opened_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "连接数"
      }
     ]
    },
    {
     "title": "关闭连接(每秒)",
     "type": "timeseries",
     "description": "连接关闭的速率。",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "targets": [
      {
       "expr": "sum(rate(rabbitmq_connections_closed_total_counter{application=\"$application\",ident=\"$ident\"}[60s]))",
       "legendFormat": "连接数"
      }
     ]
    }
   ]
  }
 ]
}